version = "2.20"
debug = true


[path]
input = "data/input"
output = "data/output"


[nlp]
lang = "en"
embeddings = "integrated"
max_distance = 200
knowledge_graph = "wordnet"


[tuning]
hypernym_min_similarity = [0.8]

# Threshold for extracting/adapting concepts
extraction_min_score = [0.7]
adaptation_min_score = [0.2]

# Of which metrics should the score consist
score_keyword_weight = [0.6]
score_semantic_similarity = [0.3]
score_wordnet_path_distance = [0.1]

# From what concepts should the metrics be derived
weight_rule_source = [0]
weight_rule_target = [0.7]
weight_original_concept = [0.3]


[wordnet]
hypernym_filter = [
    "abstraction",
    "artifact",
    "causal_agent",
    "living_thing",
    "object",
    "physical_entity",
    "psychological_feature",
    "whole",
]


[conceptnet]
bfs_node_limit = 4 
gridsearch = false # If true, the following  parameters will be ignored.

# between: Try to transfer the concept path from (adaptation origin, adaptation destination) to (current concept, adapted concept).
# within: Try to transfer the concept path from (adaptation origin, current concept) to (adaptation destination, adapted concept).
method = "between"

# difference: The vector direction between the concepts should match, i.e. min cosine(abs(vec1 - vec2), abs(vec3 - vec4)).
# similarity: The absolute similarity values of the concepts should match, i.e. min abs(cosine(vec1, vec2) - cosine(vec3, vec4)).
selector = "similarity"

[conceptnet.node]
root_form = true

[conceptnet.relation]
relax_types = false
directed = true
generalization_types = [
    "DerivedFrom",
    "IsA",
    "PartOf",
    # "HasA",
]
all_types = [
    "Antonym",
    "AtLocation",
    "CapableOf",
    "Causes",
    "CausesDesire",
    "CreatedBy",
    "DefinedAs",
    "DerivedFrom",
    "Desires",
    "DistinctFrom",
    "Entails",
    "EtymologicallyDerivedFrom",
    "EtymologicallyRelatedTo",
    "ExternalURL",
    "FormOf",
    "HasA",
    "HasContext",
    "HasFirstSubevent",
    "HasLastSubevent",
    "HasPrerequisite",
    "HasProperty",
    "HasSubevent",
    "IsA",
    "IsInstanceOf",
    "LocatedNear",
    "MadeOf",
    "MannerOf",
    "MotivatedByGoal",
    "NotCapableOf",
    "NotDesires",
    "NotHasProperty",
    "ObstructedBy",
    "PartOf",
    "ReceivesAction",
    "RelatedTo",
    "SimilarTo",
    "SymbolOf",
    "Synonym",
    "UsedFor",
]

[conceptnet.path]
[conceptnet.path.max_length]
shortest_path = 10
generalization = 3

[neo4j]
url = "neo4j://localhost:7687"
username = "neo4j"
password = "password"
