version = "2.6"
debug = true

[nlp]
lang = "en"

[path]
input = "data/input"
output = "data/output"

[adaptation]
relax_relationship_types = false
gridsearch = false # If true, the following  parameters will be ignored.

# between: Try to transfer the concept path from (adaptation origin, adaptation destination) to (current concept, adapted concept).
# within: Try to transfer the concept path from (adaptation origin, current concept) to (adaptation destination, adapted concept).
method = "within"

# difference: The vector direction between the concepts should match, i.e. min cosine(abs(vec1 - vec2), abs(vec3 - vec4)).
# similarity: The absolute similarity values of the concepts should match, i.e. min abs(cosine(vec1, vec2) - cosine(vec3, vec4)).
selector = "similarity"

[neo4j]
url = "neo4j://localhost:7687"
username = "neo4j"
password = "password"
max_relations = 10
relation_types = [
#    "Antonym",
#    "AtLocation",
    "DerivedFrom",
#    "HasA",
#    "HasProperty",
    "IsA",
    "PartOf",
#    "SimilarTo",
#    "SymbolOf",
#    "Synonym",
#    "UsedFor"
]
