version = "2.15"
debug = true


[path]
input = "data/input"
output = "data/output"


[nlp]
lang = "en"
embeddings = "integrated"
max_distance = 200

[nlp.filter.and]
# all conditions need to be fulfilled
max_conceptnet_distance = 4
min_semantic_similarity = 0.25
max_wordnet_path_distance = 10
min_wordnet_path_similarity = 0.1
min_wordnet_wup_similarity = 0.25

[nlp.filter.or]
# only one condition needs to be fulfilled
max_conceptnet_distance = 3
min_semantic_similarity = 0.5
max_wordnet_path_distance = 5
min_wordnet_path_similarity = 0.5
min_wordnet_wup_similarity = 0.5


[adaptation]
knowledge_graph = "wordnet" 
bfs_node_limit = 4 
gridsearch = false # If true, the following  parameters will be ignored.

# between: Try to transfer the concept path from (adaptation origin, adaptation destination) to (current concept, adapted concept).
# within: Try to transfer the concept path from (adaptation origin, current concept) to (adaptation destination, adapted concept).
method = "between"

# difference: The vector direction between the concepts should match, i.e. min cosine(abs(vec1 - vec2), abs(vec3 - vec4)).
# similarity: The absolute similarity values of the concepts should match, i.e. min abs(cosine(vec1, vec2) - cosine(vec3, vec4)).
selector = "similarity"


[conceptnet]
[conceptnet.node]
root_form = true

[conceptnet.relation]
relax_types = false
directed = true
generalization_types = [
    "DerivedFrom",
    "IsA",
    "PartOf",
    # "HasA",
]
all_types = [
    "Antonym",
    "AtLocation",
    "CapableOf",
    "Causes",
    "CausesDesire",
    "CreatedBy",
    "DefinedAs",
    "DerivedFrom",
    "Desires",
    "DistinctFrom",
    "Entails",
    "EtymologicallyDerivedFrom",
    "EtymologicallyRelatedTo",
    "ExternalURL",
    "FormOf",
    "HasA",
    "HasContext",
    "HasFirstSubevent",
    "HasLastSubevent",
    "HasPrerequisite",
    "HasProperty",
    "HasSubevent",
    "IsA",
    "IsInstanceOf",
    "LocatedNear",
    "MadeOf",
    "MannerOf",
    "MotivatedByGoal",
    "NotCapableOf",
    "NotDesires",
    "NotHasProperty",
    "ObstructedBy",
    "PartOf",
    "ReceivesAction",
    "RelatedTo",
    "SimilarTo",
    "SymbolOf",
    "Synonym",
    "UsedFor",
]

[conceptnet.path]
[conceptnet.path.max_length]
shortest_path = 10
generalization = 3

[neo4j]
url = "neo4j://localhost:7687"
username = "neo4j"
password = "password"
