[tool.poetry]
name = "ReCAP-Argument-Graph-Adaptation"
version = "0.1.0"
description = ""
authors = ["Mirko Lenz <info@mirko-lenz.de>"]

[tool.poetry.dependencies]
python = "^3.8"
recap-argument-graph = "^0.1.29"
neo4j = "^4.1"
scipy = "^1.5"
tomlkit = "^0.7"
wordfreq = "^2.3"
spacy = "^2.3"
textacy = "^0.10"
scikit-learn = "^0.23"
packaging = "^20.4"
sentence-transformers = "^0.3"
lmproof = "^0.3"
pendulum = "^2.1"
gibberish = "^0.4"
nltk = "^3.5"
stackprinter = "^0.2.5"
fastapi = "^0.63.0"
requests = "^2.25.1"
uvicorn = {extras = ["standard"], version = "^0.13.2"}
typer = "^0.3.2"
wn = "^0.4.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
