[tool.poetry]
name = "ReCAP-Argument-Graph-Adaptation"
version = "0.1.0"
description = ""
authors = ["Mirko Lenz <info@mirko-lenz.de>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.10"
neo4j = "^4.1"
tomlkit = "^0.7"
wordfreq = "^2.3"
textacy = "^0.11"
scikit-learn = "^0.23"
packaging = "^20.4"
lmproof = "^0.3"
pendulum = "^2.1"
nltk = "^3.5"
typer = "^0.3.2"
lemminflect = "^0.2.2"
immutables = "^0.15"
nlp-service = { path = "../NLP", develop = true }
arg-services = { path = "../Schema/python", develop = true }
arguebuf = { path = "../Argument-Graph", develop = true }

[tool.poetry.dev-dependencies]
json2python-models = "^0.2.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

# stackprinter = "^0.2.5"
# gibberish = "^0.4"
