[tool.poetry]
name = "ReCAP-Argument-Graph-Adaptation"
version = "0.1.0"
description = ""
authors = ["Mirko Lenz <info@mirko-lenz.de>"]

[tool.poetry.dependencies]
python = "^3.7"
recap-argument-graph = "^0.1.29"
neo4j = "^4.0.0a4"
scipy = "^1.4.1"
tomlkit = "^0.6.0"
wordfreq = "^2.3.2"
spacy = "^2.2.4"
textacy = "^0.10.0"
scikit-learn = "^0.22.2"
packaging = "^20.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
