[tool.poetry]
name = "ReCAP-Argument-Graph-Adaptation"
version = "0.1.0"
description = ""
authors = ["Mirko Lenz <info@mirko-lenz.de>"]

[tool.poetry.dependencies]
python = "^3.7"
recap-argument-graph = "^0.1.2"
neo4j = "^1.7.6"
tomlkit = "^0.5.8"
wordfreq = "^2.2.1"
langcodes = "^1.4.1"
spacy = "^2.2.3"
gibberish = "^0.4.0"
stackprinter = "^0.2.3"
scipy = "^1.4.1"
textacy = "^0.9.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
