[tool.poetry]
name = "arguegen"
version = "0.1.0"
description = ""
authors = ["Mirko Lenz <info@mirko-lenz.de>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
textacy = "^0.12.0"
scikit-learn = "^1.2.0"
pendulum = "^2.1.2"
nltk = "^3.8"
typer = "^0.7.0"
lemminflect = "^0.2.3"
immutables = "^0.19"
nlp-service = "^0.3.2"
arg-services = "^0.3.10"
arguebuf = "^1.2.1"
wn = "^0.9.3"
dynaconf = "^3.1.11"

[tool.poetry.dev-dependencies]
json2python-models = "^0.2.7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
